"""Pipelines to calculate tbt and HDR metrics"""
from kedro.pipeline import Pipeline, node

from .nodes import (
    populate_critical_sections_with_mcp_feedback_queries,
    get_routes_data_queries,
    prepare_data_for_metric_computation,
    compute_metrics,
    get_inspection_info_query,
    append_inspection_info,
    delete_error_logs,
    export_to_spark,
    export_to_sql,
)


def create_pipeline() -> Pipeline:
    """Creates the pipeline"""
    return Pipeline(
        [
            node(
                func=populate_critical_sections_with_mcp_feedback_queries,
                inputs=[
                    "scheduled_completed_new_runs"
                ],
                outputs=[
                    "scheduled_completed_new_runs_from_memory",
                    "scheduled_error_logs_query",
                    "scheduled_critical_sections_with_mcp_feedback_query",
                    "scheduled_critical_sections_with_mcp_feedback_history_query",
                ],
                name="populate_critical_sections_with_mcp_feedback",
            ),
            node(
                func=get_routes_data_queries,
                inputs=[
                    "scheduled_completed_new_runs_from_memory",
                ],
                outputs=[
                    "scheduled_inspection_routes_query",
                    "dummy2",
                ],
                name="get_routes_data",
            ),
            node(
                func=prepare_data_for_metric_computation,
                inputs=[
                    "scheduled_critical_sections_with_mcp_feedback",
                    "scheduled_critical_sections_with_mcp_feedback_history",
                    "scheduled_inspection_routes",
                    "dummy2"
                ],
                outputs="scheduled_metric_computation_data",
                name="prepare_data_for_metric_computation",
            ),
            node(
                func=compute_metrics,
                inputs=[
                    "scheduled_completed_new_runs_from_memory",
                    "scheduled_metric_computation_data",
                ],
                outputs=[
                    "scheduled_metrics",
                    "scheduled_bootstrap",
                    "dummy4"
                ],
                name="compute_metrics",
            ),
            node(
                func=get_inspection_info_query,
                inputs=[
                    "scheduled_completed_new_runs_from_memory",
                    "dummy4"

                ],
                outputs=[
                    "scheduled_inspection_info_query",
                    "dummy5"
                ],
                name="get_inspection_info_query",
            ),
            node(
                func=append_inspection_info,
                inputs=[
                    "scheduled_inspection_info",
                    "scheduled_metrics",
                    "dummy5"
                ],
                outputs=[
                    "scheduled_metrics_with_inspection_info",
                    "dummy6"
                ],
                name="append_inspection_info",
            ),
            node(
                func=export_to_sql,
                inputs=[
                    "scheduled_metrics_with_inspection_info",
                    "scheduled_critical_sections_with_mcp_feedback",
                    "scheduled_error_logs",
                    "dummy6"
                ],
                outputs=[
                    "scheduled_metrics_sql",
                    "scheduled_critical_sections_with_mcp_feedback_sql",
                    "scheduled_error_logs_history_sql",
                    "dummy7"
                ],
                name="export_to_sql",
            ),
            node(
                func=export_to_spark,
                inputs=[
                    "scheduled_metrics_with_inspection_info",
                    "scheduled_bootstrap",
                    "scheduled_critical_sections_with_mcp_feedback",
                    "scheduled_error_logs",
                    "dummy7"
                ],
                outputs=[
                    "scheduled_metrics_spark",
                    "scheduled_critical_sections_with_mcp_feedback_spark",
                    "scheduled_error_logs_history_spark",
                    "scheduled_bootstrap_spark",
                    "scheduled_spark_ok",
                ],
                name="export_to_spark",
            ),
            node(
                func=delete_error_logs,
                inputs=[
                    "scheduled_completed_new_runs_from_memory",
                    "params:tbt_db",
                    "scheduled_spark_ok",
                ],
                outputs="scheduled_delete_error_logs_result",
                name="delete_error_logs",
            ),
        ]
    )
